<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: draft/protos/ydb_view.proto

namespace GPBMetadata\Draft\Protos;

class YdbView
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Protos\Annotations\Validation::initOnce();
        \GPBMetadata\Protos\YdbOperation::initOnce();
        \GPBMetadata\Protos\YdbScheme::initOnce();
        $pool->internalAddGeneratedFile(
            '
∫
draft/protos/ydb_view.protoYdb.Viewprotos/ydb_operation.protoprotos/ydb_scheme.proto"d
DescribeViewRequest9
operation_params (2.Ydb.Operations.OperationParams
path (	BêÊ*"D
DescribeViewResponse,
	operation (2.Ydb.Operations.Operation"I
DescribeViewResult
self (2.Ydb.Scheme.Entry

query_text (	B]
tech.ydb.proto.draft.viewZ=github.com/ydb-platform/ydb-go-genproto/draft/protos/Ydb_View¯bproto3'
        , true);

        static::$is_initialized = true;
    }
}

