<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: draft/ydb_view_v1.proto

namespace GPBMetadata\Draft;

class YdbViewV1
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Draft\Protos\YdbView::initOnce();
        $pool->internalAddGeneratedFile(
            '
ê
draft/ydb_view_v1.protoYdb.View.V12\\
ViewServiceM
DescribeView.Ydb.View.DescribeViewRequest.Ydb.View.DescribeViewResponseB\\
tech.ydb.proto.draft.view.v1Z9github.com/ydb-platform/ydb-go-genproto/draft/Ydb_View_V1øbproto3'
        , true);

        static::$is_initialized = true;
    }
}

