<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: draft/protos/ydb_view.proto

namespace Ydb\View;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Ydb.View.DescribeViewResponse</code>
 */
class DescribeViewResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The result of the request will be inside the operation
     *
     * Generated from protobuf field <code>.Ydb.Operations.Operation operation = 1;</code>
     */
    protected $operation = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ydb\Operations\Operation $operation
     *           The result of the request will be inside the operation
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Draft\Protos\YdbView::initOnce();
        parent::__construct($data);
    }

    /**
     * The result of the request will be inside the operation
     *
     * Generated from protobuf field <code>.Ydb.Operations.Operation operation = 1;</code>
     * @return \Ydb\Operations\Operation|null
     */
    public function getOperation()
    {
        return $this->operation;
    }

    public function hasOperation()
    {
        return isset($this->operation);
    }

    public function clearOperation()
    {
        unset($this->operation);
    }

    /**
     * The result of the request will be inside the operation
     *
     * Generated from protobuf field <code>.Ydb.Operations.Operation operation = 1;</code>
     * @param \Ydb\Operations\Operation $var
     * @return $this
     */
    public function setOperation($var)
    {
        GPBUtil::checkMessage($var, \Ydb\Operations\Operation::class);
        $this->operation = $var;

        return $this;
    }

}

