<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: draft/protos/ydb_view.proto

namespace Ydb\View;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Ydb.View.DescribeViewResult</code>
 */
class DescribeViewResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Description of a generic scheme object
     *
     * Generated from protobuf field <code>.Ydb.Scheme.Entry self = 1;</code>
     */
    protected $self = null;
    /**
     * Text of the view query
     *
     * Generated from protobuf field <code>string query_text = 2;</code>
     */
    protected $query_text = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Ydb\Scheme\Entry $self
     *           Description of a generic scheme object
     *     @type string $query_text
     *           Text of the view query
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Draft\Protos\YdbView::initOnce();
        parent::__construct($data);
    }

    /**
     * Description of a generic scheme object
     *
     * Generated from protobuf field <code>.Ydb.Scheme.Entry self = 1;</code>
     * @return \Ydb\Scheme\Entry|null
     */
    public function getSelf()
    {
        return $this->self;
    }

    public function hasSelf()
    {
        return isset($this->self);
    }

    public function clearSelf()
    {
        unset($this->self);
    }

    /**
     * Description of a generic scheme object
     *
     * Generated from protobuf field <code>.Ydb.Scheme.Entry self = 1;</code>
     * @param \Ydb\Scheme\Entry $var
     * @return $this
     */
    public function setSelf($var)
    {
        GPBUtil::checkMessage($var, \Ydb\Scheme\Entry::class);
        $this->self = $var;

        return $this;
    }

    /**
     * Text of the view query
     *
     * Generated from protobuf field <code>string query_text = 2;</code>
     * @return string
     */
    public function getQueryText()
    {
        return $this->query_text;
    }

    /**
     * Text of the view query
     *
     * Generated from protobuf field <code>string query_text = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setQueryText($var)
    {
        GPBUtil::checkString($var, True);
        $this->query_text = $var;

        return $this;
    }

}

